# Generated by Django 3.2.10 on 2022-02-01 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oderstatus',
            old_name='status',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='shippingstatus',
            old_name='status',
            new_name='name',
        ),
    ]
