# Generated by Django 3.2.10 on 2022-02-01 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productoptionimage_table'),
        ('users', '0002_auto_20220127_0909'),
        ('orders', '0002_auto_20220201_1336'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OderItem',
            new_name='OrderItem',
        ),
        migrations.RenameModel(
            old_name='OderStatus',
            new_name='OrderStatus',
        ),
    ]
