# Generated by Django 3.2.10 on 2022-02-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20220201_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='tracking_number',
            field=models.CharField(max_length=45, null=True, unique=True),
        ),
    ]
