# Generated by Django 3.2.10 on 2022-02-01 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220127_0909'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productoptionimage',
            table='product_option_images',
        ),
    ]
