# Generated by Django 3.2.10 on 2022-02-07 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productoptionimage_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TypeImage',
        ),
    ]
